name: "Publish Aliyun Backup"

on:
  push:
    branches:
      - main
    paths:
      - 'addons/aliyun_backup/**'
  workflow_dispatch:

jobs:
  build:
    name: Docker Image build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: home-assistant/builder/actions/build-image@2026.03.2
        with:
          context: addons/aliyun_backup
          image: ghcr.io/happyks/addon-aliyun-backup
          version: "1.0.16"
          architectures: "aarch64"
